services:
  # Go server with hot reload
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - /app/tmp
    environment:
      - HOST=0.0.0.0
      - PORT=4000
      - GIN_MODE=debug
    networks:
      - backend-playground
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React client with hot reload
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000
      - VITE_HOST=0.0.0.0
      - VITE_PORT=4200
    networks:
      - backend-playground
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped

networks:
  backend-playground:
    driver: bridge

volumes:
  server_node_modules:
  client_node_modules:
