services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: backend2lab-server-dev
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4000
    working_dir: /app
    command: npm run dev
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: backend2lab-client-dev
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped
    depends_on:
      - server
