#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
git lfs pre-push "$@"

# Execute tests before pushing

npm test --prefix server
npm test --prefix client

if [ $? -ne 0 ]; then
echo "❌ Tests failed. Not allowing the push. Please fix the errors and try again."
exit 1
fi

echo "✅ Tests passed. Allowing the push."
exit 0
